name: Pyright

on:
  push:
    paths:
      - 'md2html.py'
      - 'mdtohtml.py'
  pull_request:
    paths:
      - 'md2html.py'
      - 'mdtohtml.py'

jobs:
   analyse-pyright:
    name: Pyright on Windows with python ${{ matrix.python-version }}
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.12.2", "3.10", "3.11.1"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyright
        pip install -r requirements.txt
    - name: Analysing the code with pyright
      run: |
        pyright
